[project]
name = "infra"
revision = "1.0"
require_reason = false

[providers]
infra = "onepassword://Infra"

[profiles.default]
SSH_PRIVATE_CONFIG = { description = "Private SSH configuration", required = true, providers = ["infra"] }
SSH_CACHIX_CONFIG = { description = "Cachix SSH configuration", required = true, providers = ["infra"] }
