# Hardware profile for MacBook Pro 9,2 (13-inch, Mid 2012, Ivy Bridge).
# Generated by `nixos-generate-config`.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ahci"
    "usb_storage"
    "usbhid"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/mapper/luks-de105c3f-9ec0-4225-80d0-689b2d2c8e71";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-de105c3f-9ec0-4225-80d0-689b2d2c8e71".device =
    "/dev/disk/by-uuid/de105c3f-9ec0-4225-80d0-689b2d2c8e71";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/E8C8-F6FD";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  boot.initrd.luks.devices."luks-6a8b372f-54ea-42e6-a353-b2f727e97210".device =
    "/dev/disk/by-uuid/6a8b372f-54ea-42e6-a353-b2f727e97210";

  swapDevices = [
    { device = "/dev/mapper/luks-6a8b372f-54ea-42e6-a353-b2f727e97210"; }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
